### ISSUE TITLE
Issues Utilizing UniversalDashboard.Markdown

### ISSUE THREAD

**Issue by the-mentor** [AlonGvili/UniversalDashboard.Markdown#3]
Hi @AlonGvili  I've installed UniversalDashboard.Markdown from the PSGallery and imported it to my UD project and the New-UDMarkdown doesnt seem to show anything.
I've even used your example code in the README.md file.
I'm running 

UniversalDashboard.Community 2.5.3
UniversalDashboard.Markdown 1.1.0

Thank you.
-DM

**Comment by AlonGvili** [comment]
I will take a look tonight

**Comment by the-mentor** [comment]
Thank you very much @alongvili!
FYI I'm also from 🇮🇱 

-DM

**Comment by adamdriscoll** [comment]
@AlonGvili @the-mentor This is fixed in this PR: https://github.com/AlonGvili/UniversalDashboard.Markdown/pull/4

**Comment by AlonGvili** [comment]
@adamdriscoll thank you adam for this pr

_Sent from my P20 Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
