### ISSUE TITLE
Unable to load in Edge

### ISSUE THREAD

**Issue by bbomgardner** [AlonGvili/UniversalDashboard.Markdown#6]
Hi Alon! Thank you very much for you work on this plugin!

The current version does not seem to work in Edge for me. When I run the demo page locally after building UD reports `Component not registered: ud-markdown`

In the js console of the browser I am getting an error:

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
```

https://github.com/AlonGvili/UniversalDashboard.Markdown/blob/27618cf6f7d146ef45523585ee938a714a9fe4d1/Source/App/components/blockquote/blockquote.js#L11

Thoughts?

**Comment by AlonGvili** [comment]
i will check this tomorrow , and trying to fix that bug

**Comment by AlonGvili** [comment]
this was fixed in the last release
